### PR TITLE
premake5: add arch suffix to library names

### PR DESCRIPTION
**Pull request by iZarif**

### CODE REVIEW

**Comment by nekonomicon** [comment]
Is it possible to check `$CC -v`, `$CC -dumpmachine`, `$ARCH` or `$TARGET`?
Or even ask user about `$ARCH`?

**Comment by iZarif** [comment]
> Is it possible to check `$CC -v`, `$CC -dumpmachine`, `$ARCH` or `$TARGET`? Or even ask user about `$ARCH`?

`$CC` is not always set, and if it is, it may not match the compiler that premake will use. Will `-dumpmachine` work better than `uname`? Asking the user about `$ARCH` is definitely a good idea, I was going to do it.

**Comment by mittorn** [comment]
uname will show host architecture, dumpmachine shows target.
how do you want to compile without $CC?

**Comment by iZarif** [comment]
> How do you want to compile without $CC?

In Premake there is no (or I have not found) way to get the path to the selected compiler, so there is no $CC

**Comment by iZarif** [comment]
> Or even ask user about `$ARCH`?

Done, user can now specify the architecture using the --arch option

**Comment by iZarif** [comment]
> That's incorrect.
> 
> You have to compile build.h, get all defined macros and select suffix according to engine/common/build.c.

Done, now if the user did not specify a compiler explicitly then gcc is implied. If the user does not have gcc installed the user will have to specify the architecture manually using the --arch option

**Comment by FreeSlave** [comment]
Honestly I don't understand why we need any "contrib" stuff in this repo. Those who want alternative ways to build hlsdk can just keep it in their forks and merge/rebase upon master when needed.

**Comment by iZarif** [comment]
> Honestly I don't understand why we need any "contrib" stuff in this repo. Those who want alternative ways to build hlsdk can just keep it in their forks and merge/rebase upon upstream master when needed.

I was just offering, I don't force anyone to merge it

**Pull request merged**
