### PR TITLE
Ignore dlls, pdb, some cmake generated files and orig files produced …

### PR DESCRIPTION
**Pull request by FreeSlave**
…by some diff programs

### CODE REVIEW

**Comment by a1batross** [comment]
You can also add here vsxproj, vsproj, sln, as they are generated.

**Comment by FreeSlave** [comment]
Generated by what? I thought our cmake script does not support msvc now.

**Comment by a1batross** [comment]
There is nothing special in supporting MSVC.

**Comment by FreeSlave** [comment]
Added.
Btw, what do you think of removing some original xash3d sdk leftovers?

**Comment by a1batross** [comment]
Is there any leftovers? It's a hlsdk for xash3d engine in first place.

**Comment by nekonomicon** [comment]
@FreeSlave, Do you mean headers and props? It's useful for modders.

**Comment by FreeSlave** [comment]
I mean .bat, .lst and .dsw files in the repository root. And also gnu.txt (hlsdk is not gpl anyway)

**Comment by a1batross** [comment]
Some headers are GPL licensed(like com_model.h) and have nothing to do with HLSDK. There is just two licenses, although I don't know are they compatible. I'm not a lawyer.

Yes, I think, outdated rubbish can be removed.

**Pull request merged**
