### PR TITLE
Blue Shift

### PR DESCRIPTION
**Pull request by nekonomicon**

### CODE REVIEW

**Comment by MyLittleRobo** [comment]
Note: should be merged to FWGS:blueshift, not master. Probably repo admins should create such branch themselves.

**Comment by a1batross** [comment]
It may be added in blueshift directory in master branch, like Valve did it for dmc and ricochet in newer sdk.

**Comment by MyLittleRobo** [comment]
@a1batross I'm not sure this is good idea. It will make applying patches to hl more complicated (must apply same fixes to both source trees, while when it's in separate branch all you need is just a merge). Probably this makes sense for ricochet and dmc, since they are diverse from hl, but Blue shift code is practically the same, so branch looks like a better option.

**Comment by nekonomicon** [comment]
Maybe use macros https://github.com/ptitSeb/halflife/commit/f4b0b36b141a84b150327297177a254fd93963ef ?

**Comment by fuzun** [comment]
Halted?

**Comment by nekonomicon** [comment]
Any suggestions? Separate folder, branch or macros? I can create other PR, if needed.

**Comment by a1batross** [comment]
Merged to blueshift branch.

**Pull request closed without merging**
