### PR TITLE
Add deny noise for func_recharger and func_healthcharger, when activator's health/armor is full

### PR DESCRIPTION
**Pull request by tyabus**

### CODE REVIEW

**Comment by a1batross** [comment]
It's from these bugs, which makes Half-Life is so Half-Life.

**Comment by tyabus** [comment]
> It's from these bugs, which makes Half-Life is so Half-Life.
I think this is not a bug, that is a enchancement

**Comment by a1batross** [comment]
>I think this is not a bug, that is a enchancement

Too noticable enchancements should be in mods.

**Comment by tyabus** [comment]
> > I think this is not a bug, that is a enchancement
> 
> Too noticable enchancements should be in mods.

this is a joke?

**Comment by nekonomicon** [comment]
Nope. You can place any enhancements under macro or use cvars.

**Comment by tyabus** [comment]
> Nope. You can place any enhancements under macro or use cvars.

I don't want to put this under macro/cvar, because this enhancement is very tiny. Can you pull this without any cvars/macros?

**Comment by nekonomicon** [comment]
bhop, weapon bobbing and selfgauss fix has one string changes too and was put under cvars.

**Comment by FreeSlave** [comment]
We are mostly fixing bugs in the master branch, not make enhancements. And if you ask people if the original behavior of chargers is a bug or not, opinions will be different. I think It's a matter of taste.
By the way `MAX_NORMAL_BATTERY` and `pActivator->pev->max_health` exist to avoid magic numbers.
There're a lot of things that can be enhanced in Half-Life but better keep them in mods.

**Comment by tyabus** [comment]
oops, i haven't done putting this under cvar

**Comment by nekonomicon** [comment]
@tyabus, you can use the following commands to edit the latest commit:
```git add <changed files>
git commit --amend```

**Comment by a1batross** [comment]
@nekonomicon 

and `git push --force`. Force push is literally a bad thing, but may be good to keep history clean. 

But I think, commits must be atomic and change only one thing.

**Comment by tyabus** [comment]
Done.

**Pull request merged**
