### PR TITLE
replace gnu.txt with LICENSE from ValveSoftware/halflife

### PR DESCRIPTION
**Pull request by iZarif**

### CODE REVIEW

**Comment by nekonomicon** [comment]
@iZarif gnu.txt was in archive with original xash3d.
HLSDK licensed under Valve's EULA.
https://github.com/ValveSoftware/halflife/blob/master/LICENSE
https://github.com/FWGS/hlsdk-xash3d/blob/master/dlls/cbase.h#L1

**Comment by iZarif** [comment]
Maybe we should just delete this file?

**Comment by nekonomicon** [comment]
Yes

**Comment by a1batross** [comment]
Maybe adding Half-Life SDK license file instead?

**Pull request merged**
