### PR TITLE
Remove unneded headers under GPLv3. Upload some headers from original hlsdk 2.3.

### PR DESCRIPTION
**Pull request by nekonomicon**

### CODE REVIEW

**Comment by a1batross** [comment]
As this repo is hlsdk-xash3d(Xash3D's HLSDK), everything Xash3D-only features, like extended APIs, must be kept. I don't know how, rewritten or else.

**Comment by nekonomicon** [comment]
Xash3D's HLSDK uses only features from mobility_int.h and physint.h(it seems for props).
I removed headers which uses with engine and menu.
Also, try compare hlsdk headers with quake headers. It's partially identical.

**Comment by nekonomicon** [comment]
Mistake.

**Comment by mittorn** [comment]
@a1batross, why? It is HLSDK, not XashXT. It is better to remove all GPLv3 code.

**Comment by a1batross** [comment]
@mittorn It's can be a base.

Not all features from XashXT are needed for mod. Sometimes it's a two-three
functions, like Render Interface used in cs16-client.

**Comment by mittorn** [comment]
@a1batross It is already a base for mod porting. Just apply some mod as patch for it. So we need to fix all license conflicts.

**Pull request closed without merging**
